[project]
name = "jarvis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autopep8>=2.3.2",
    "fastapi[standard]>=0.117.1",
    "sqlalchemy>=2.0.43",
    "sqlmodel>=0.0.25",
    "tzdata>=2025.2",
]
