# Generated by Django 5.2.6 on 2025-09-28 14:35

import food_tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(db_index=True, max_length=255)),
                ('calories', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('created_date', models.DateTimeField(default=food_tracker.models.kolkata_now)),
            ],
            options={
                'db_table': 'food_logs',
            },
        ),
    ]
