# Generated by Django 5.2.6 on 2025-09-29 20:33

import django.db.models.deletion
import workout_tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=workout_tracker.models.kolkata_now)),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Workout Session', max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=workout_tracker.models.kolkata_now)),
            ],
            options={
                'db_table': 'workouts',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(default=1)),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=workout_tracker.models.kolkata_now)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sets', to='workout_tracker.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workout_tracker.workout')),
            ],
            options={
                'db_table': 'workout_sets',
                'ordering': ['workout', 'exercise', 'set_number'],
            },
        ),
    ]
