# Generated by Django 5.2.6 on 2025-09-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='reps',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight',
            field=models.FloatField(default=20, help_text='Weight in kg'),
        ),
    ]
